### ISSUE TITLE
注入流动资金时，报错

### ISSUE THREAD

**Issue by jiangying000** [Elements-Studio/starswap-core#40]
**Bug Description**
注入流动资金时，报错
内容是：
ALERT: Starmask: contract.dry_run_raw failed. Error: {"ExecutionFailure":{"code_offset":4,"function":54,"function_name":"withdraw_with_metadata","location":{"Module":{"address":"0x00000000000000000000000000000001","name":"Account"}},"status":4008,"status_code":"MISSING_DATA"}}

**Comment by ValentineReese** [comment]
这边的输入参数麻烦提供一下？

**Comment by jiangying000** [comment]
过了太久忘了，下次复现时在这里更新

**Comment by jiangying000** [comment]
接受1%滑点（默认0.2%），注入5000stc，报错
![image](https://user-images.githubusercontent.com/23182033/182093674-264dca78-be1d-46ab-beed-99891721fd25.png)

![image](https://user-images.githubusercontent.com/23182033/182093657-891426a9-c18d-4a06-aebf-ccca2d9bf25c.png)

**Comment by ValentineReese** [comment]
这边确定一下你的STC和XUSDT是否都已经存在并且足额？

**Comment by jiangying000** [comment]
明白了，要先在 https://starswap.xyz/#/swap 兑换，注入操作不会自动兑换，谢谢

建议：可以在用户供应界面检测两种币是否足额，如果不足额给个提示，supply按钮变灰，不让用户按，也不用给出确认界面。

**Comment by ValentineReese** [comment]
收到
