### ISSUE TITLE
Starswap STAR回购合约

### ISSUE THREAD

**Issue by element2050** [Elements-Studio/starswap-core#46]
**Is your feature request related to a problem? Please describe.**
由社区提议的，经过投票，申请了100万的STC，发起STAR的回购，整个回购持续1年。

Starswap 在社区版最终回购策略出来前，有个初步方案会先跑起来，具体策略是：将100万STC Grant平摊到每天，每天累计回购2741 STC等值的STAR，为了避免套利，一天内的回购分多次触发，每5min回购一次，每次回购9.52 STC等值的STAR，回购持续2周。预计两周累计回购38384 STC等值的STAR。此次回购周期从2022-7-29号开始，持续到8-14号。

**Describe the solution you'd like**
回购的策略：关键就两个参数，一个是单次回购数量，一个是回购周期，直到把grant的资金回购完。
考虑把回购流程合约化，任意社区用户都可以调用，调用时候把当前时间之前还没回购的额度全部购买，购买资金来自回购国库。
回购数量和回购周期实现配置化。
回购来的STAR，先保留在回购账号的Balance下，待社区投票后，再决定如何使用（是锁仓还是其它用途）。

回购最终会DAO化，也可以提前考虑下。

**Comment by welbon** [comment]
1. 滑点问题，需要讨论滑点的数值；由于在swap中将STAR转成STC的时候会存在滑点问题。当前可以确定一个固定的滑点以适配当前深度，不排除池子深度突然变浅导致滑点不可用的问题，从而导致兑换失败，进而导致回购失败的问题。
2. DAO化之后，回购账号Balance升级导致不可签名的问题。

**Comment by ValentineReese** [comment]
目前存在两个问题
1. 滑点问题，需要讨论滑点的数值；由于在swap中将STAR转成STC的时候会存在滑点问题。当前可以确定一个固定的滑点以适配当前深度，不排除池子深度突然变浅导致滑点不可用的问题，从而导致兑换失败，进而导致回购失败的问题。
2. DAO化之后，回购账号Balance升级导致不可签名的问题。

**Comment by element2050** [comment]
complete via [#47 ](https://github.com/Elements-Studio/starswap-core/pull/47)
