### ISSUE TITLE
License not specified, making the code closed source

### ISSUE THREAD

**Issue by villesundell** [Elements-Studio/starswap-core#79]
**Bug Description**
License is not specified, making the code essentially closed source.

This can be fixed in many ways, the most common being a LICENSE file in the root of the repo (recognized by GitHub). [GitHub guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Expected Behavior**
The license should be clearly visible, for example at the [root](https://github.com/Elements-Studio/starswap-core) of the repo.

**Additional Context**
If the author does not specify a license, the rights to the work are 100% owned and controlled by the author.

**Comment by ValentineReese** [comment]
Got it, this will be fixed soon

**Comment by ValentineReese** [comment]
This has been fixed
